<!--

  WARNING:

  本内容由 DeepSeek 生成。

  This content is generated by DeepSeek AI。

-->
<script setup>
import { ref, computed, onBeforeUnmount } from 'vue'

// ---------- Props ----------
const props = defineProps({
  // 要显示的颜色，格式 #RRGGBB
  displayColor: {
    type: String,
    required: true,
    validator: (val) => /^#[0-9a-fA-F]{6}$/.test(val),
  },
  // 显示样式，目前仅支持 'block'（小正方形）
  itemStyle: {
    type: String,
    default: 'block',
  },
})

// ---------- 状态 ----------
// 当前显示的文本（颜色值 或 “复制成功”）
const displayText = ref(props.displayColor)

// 定时器句柄
let timer = null

// ---------- 计算属性 ----------
// 色块样式
const blockStyle = computed(() => {
  const isBlock = props.itemStyle === 'block'
  return {
    backgroundColor: props.displayColor,
    display: 'inline-block',
    width: isBlock ? '1.2em' : '1.2em',
    height: isBlock ? '1.2em' : '1.2em',
    borderRadius: isBlock ? '2px' : '2px',
    cursor: 'pointer',
    verticalAlign: 'middle',
    marginRight: '6px',
    border: '1px solid rgba(0, 0, 0, 0.15)',
    flexShrink: 0,
    transition: 'transform 0.1s, box-shadow 0.1s',
  }
})

// ---------- 方法 ----------
// 复制颜色值
const handleCopy = async () => {
  // 如果当前显示的是“复制成功”，不重复触发
  if (displayText.value === '复制成功') return

  const color = props.displayColor

  // 尝试使用 Clipboard API
  try {
    await navigator.clipboard.writeText(color)
    onCopySuccess()
  } catch (_) {
    // 降级方案：使用 document.execCommand
    try {
      const textarea = document.createElement('textarea')
      textarea.value = color
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      textarea.style.pointerEvents = 'none'
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      onCopySuccess()
    } catch (__) {
      console.error('[selColor] 复制失败:', color)
    }
  }
}

// 复制成功后的处理
const onCopySuccess = () => {
  displayText.value = '复制成功'
  clearTimeout(timer)
  timer = setTimeout(() => {
    displayText.value = props.displayColor
  }, 2000)
}

// ---------- 生命周期 ----------
onBeforeUnmount(() => {
  if (timer) clearTimeout(timer)
})
</script>

<template>
  <span class="sel-color-wrapper">
    <!-- 色块 -->
    <span
      class="color-block"
      :style="blockStyle"
      @click="handleCopy"
      :title="`点击复制 ${displayColor}`"
      role="button"
      tabindex="0"
      @keydown.enter="handleCopy"
    />
    <!-- 颜色值文本 -->
    <span class="color-text">{{ displayText }}</span>
  </span>
</template>

<style scoped>
.sel-color-wrapper {
  display: inline-flex;
  align-items: center;
  font-family: 'SF Mono', 'Fira Code', 'Consolas', 'Monaco', monospace;
  font-size: 0.9em;
  line-height: 1.5;
  white-space: nowrap;
}

.color-block {
  /* 鼠标悬停时加深边框，提升交互感 */
  transition: border-color 0.15s, transform 0.1s, box-shadow 0.1s;
}
.color-block:hover {
  border-color: rgba(0, 0, 0, 0.35);
  box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.05);
}
.color-block:active {
  transform: scale(0.92);
}

.color-text {
  /* 让文本像普通文本一样可以被鼠标划选 */
  user-select: text;
  cursor: text;
  font-size: inherit;
  font-family: inherit;
  color: inherit;
}

/* 当显示 “复制成功” 时，给一点颜色反馈 */
.color-text:not(:empty) {
  transition: color 0.2s;
}
</style>